# Generated by Django 3.2.7 on 2021-10-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riders',
            name='password1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='riders',
            name='password2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
