# Generated by Django 3.2.7 on 2021-11-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
    ]
